// ============================================================================
// ISCO-08 Mapping — International Standard Classification of Occupations
// Maps our role titles to ISCO-08 2-digit codes for Eurostat salary lookups
// isTech flag: if true, apply sectorAdjustment_J when using Eurostat data
// ============================================================================

export const ROLE_TO_ISCO: Record<string, { isco: string; isTech: boolean }> = {
  // ISCO 25 — ICT Professionals
  'Software Engineer': { isco: '25', isTech: true },
  'Software Developer': { isco: '25', isTech: true },
  'Frontend Developer': { isco: '25', isTech: true },
  'Backend Developer': { isco: '25', isTech: true },
  'Full Stack Developer': { isco: '25', isTech: true },
  'DevOps Engineer': { isco: '25', isTech: true },
  'Cloud Engineer': { isco: '25', isTech: true },
  'Cloud Architect': { isco: '25', isTech: true },
  'Data Engineer': { isco: '25', isTech: true },
  'Data Scientist': { isco: '25', isTech: true },
  'AI Engineer': { isco: '25', isTech: true },
  'Machine Learning Engineer': { isco: '25', isTech: true },
  'NLP Engineer': { isco: '25', isTech: true },
  'Computer Vision Engineer': { isco: '25', isTech: true },
  'MLOps Engineer': { isco: '25', isTech: true },
  'LLM Engineer': { isco: '25', isTech: true },
  'Database Administrator': { isco: '25', isTech: true },
  'Database Architect': { isco: '25', isTech: true },
  'Network Engineer': { isco: '25', isTech: true },
  'Network Architect': { isco: '25', isTech: true },
  'Cybersecurity Analyst': { isco: '25', isTech: true },
  'Security Engineer': { isco: '25', isTech: true },
  'Security Architect': { isco: '25', isTech: true },
  'Penetration Tester': { isco: '25', isTech: true },
  'Solutions Architect': { isco: '25', isTech: true },
  'Enterprise Architect': { isco: '25', isTech: true },
  'Site Reliability Engineer': { isco: '25', isTech: true },
  'Platform Engineer': { isco: '25', isTech: true },
  'Infrastructure Engineer': { isco: '25', isTech: true },
  'Release Engineer': { isco: '25', isTech: true },
  'Mobile Developer': { isco: '25', isTech: true },
  'Game Developer': { isco: '25', isTech: true },
  'AR/VR Developer': { isco: '25', isTech: true },
  'Blockchain Developer': { isco: '25', isTech: true },
  'Embedded Systems Engineer': { isco: '25', isTech: true },
  'IoT Engineer': { isco: '25', isTech: true },
  'Robotics Engineer': { isco: '25', isTech: true },
  'Data Analyst': { isco: '25', isTech: true },
  'Analytics Engineer': { isco: '25', isTech: true },
  'BI Analyst': { isco: '25', isTech: true },
  'BI Developer': { isco: '25', isTech: true },
  'ETL Developer': { isco: '25', isTech: true },
  'Data Platform Engineer': { isco: '25', isTech: true },
  'Salesforce Developer': { isco: '25', isTech: true },
  'Salesforce Administrator': { isco: '25', isTech: true },
  'SAP Consultant': { isco: '25', isTech: true },
  'ServiceNow Developer': { isco: '25', isTech: true },
  'RPA Developer': { isco: '25', isTech: true },
  'Automation Engineer': { isco: '25', isTech: true },
  'Low-Code Developer': { isco: '25', isTech: true },
  'API Developer': { isco: '25', isTech: true },
  'Integration Engineer': { isco: '25', isTech: true },
  'AI Solutions Architect': { isco: '25', isTech: true },
  'AI Consultant': { isco: '25', isTech: true },
  'AI Strategist': { isco: '25', isTech: true },
  'AI Research Scientist': { isco: '25', isTech: true },
  'AI Ethics Researcher': { isco: '25', isTech: true },
  'Prompt Engineer': { isco: '25', isTech: true },
  'Data Annotator': { isco: '25', isTech: true },
  'AI Trainer': { isco: '25', isTech: true },
  'QA Engineer': { isco: '25', isTech: true },
  'Web Developer': { isco: '25', isTech: true },

  // ISCO 35 — ICT Technicians
  'IT Support Specialist': { isco: '35', isTech: true },
  'Help Desk': { isco: '35', isTech: true },
  'Systems Administrator': { isco: '35', isTech: true },
  'Technical Support Engineer': { isco: '35', isTech: true },

  // ISCO 12 — Administrative & Commercial Managers
  'Marketing Manager': { isco: '12', isTech: false },
  'Digital Marketing Manager': { isco: '12', isTech: false },
  'Sales Manager': { isco: '12', isTech: false },
  'Human Resources Manager': { isco: '12', isTech: false },
  'HR Manager': { isco: '12', isTech: false },
  'Operations Manager': { isco: '12', isTech: false },
  'Brand Manager': { isco: '12', isTech: false },
  'Growth Marketing Manager': { isco: '12', isTech: false },
  'Performance Marketing Manager': { isco: '12', isTech: false },
  'Revenue Operations Manager': { isco: '12', isTech: false },
  'Customer Success Manager': { isco: '12', isTech: false },

  // ISCO 13 — Production & Specialized Services Managers
  'IT Manager': { isco: '13', isTech: true },
  'IT Director': { isco: '13', isTech: true },
  'Engineering Manager': { isco: '13', isTech: true },
  'VP of Engineering': { isco: '13', isTech: true },
  'CTO': { isco: '13', isTech: true },
  'Chief Technology Officer': { isco: '13', isTech: true },
  'Chief Data Officer': { isco: '13', isTech: true },
  'Product Manager': { isco: '13', isTech: true },
  'Technical Product Manager': { isco: '13', isTech: true },
  'Technical Program Manager': { isco: '13', isTech: true },
  'Project Manager': { isco: '13', isTech: false },
  'Program Manager': { isco: '13', isTech: false },
  'IT Project Manager': { isco: '13', isTech: true },
  'Portfolio Manager': { isco: '13', isTech: false },
  'Scrum Master': { isco: '13', isTech: true },
  'Agile Coach': { isco: '13', isTech: true },
  'Technical Lead': { isco: '13', isTech: true },
  'Staff Engineer': { isco: '13', isTech: true },
  'Principal Engineer': { isco: '13', isTech: true },
  'Design Manager': { isco: '13', isTech: true },
  'Chief of Staff': { isco: '13', isTech: false },
  'Fractional CTO': { isco: '13', isTech: true },

  // ISCO 21 — Science & Engineering Professionals
  'Civil Engineer': { isco: '21', isTech: false },
  'Mechanical Engineer': { isco: '21', isTech: false },
  'Electrical Engineer': { isco: '21', isTech: false },

  // ISCO 24 — Business & Administration Professionals
  'Accountant': { isco: '24', isTech: false },
  'Financial Analyst': { isco: '24', isTech: false },
  'Business Analyst': { isco: '24', isTech: false },
  'Management Consultant': { isco: '24', isTech: false },
  'Strategy Consultant': { isco: '24', isTech: false },
  'Recruiter': { isco: '24', isTech: false },
  'Talent Acquisition Specialist': { isco: '24', isTech: false },
  'Technical Recruiter': { isco: '24', isTech: true },
  'Compliance Manager': { isco: '24', isTech: false },
  'GRC Analyst': { isco: '24', isTech: false },
  'Implementation Consultant': { isco: '24', isTech: false },
  'ERP Consultant': { isco: '24', isTech: false },
  'Transformation Manager': { isco: '24', isTech: false },
  'Change Manager': { isco: '24', isTech: false },
  'Sustainability Manager': { isco: '24', isTech: false },
  'ESG Analyst': { isco: '24', isTech: false },
  'Diversity & Inclusion Manager': { isco: '24', isTech: false },
  'Venture Capital Analyst': { isco: '24', isTech: false },
  'Training Manager': { isco: '24', isTech: false },
  'Learning & Development Manager': { isco: '24', isTech: false },
  'Technical Enablement Engineer': { isco: '24', isTech: true },
  'Developer Relations': { isco: '24', isTech: true },
  'Developer Advocate': { isco: '24', isTech: true },

  // ISCO 26 — Legal, Social & Cultural Professionals
  'UX Designer': { isco: '26', isTech: true },
  'UI Designer': { isco: '26', isTech: true },
  'Product Designer': { isco: '26', isTech: true },
  'UX Researcher': { isco: '26', isTech: true },
  'Graphic Designer': { isco: '26', isTech: false },
  'Technical Writer': { isco: '26', isTech: true },

  // ISCO 33 — Business Associate Professionals
  'Account Executive': { isco: '33', isTech: false },
  'Sales Representative': { isco: '33', isTech: false },
  'Business Development Representative': { isco: '33', isTech: false },
  'BDR': { isco: '33', isTech: false },
  'SDR': { isco: '33', isTech: false },
  'Sales Engineer': { isco: '33', isTech: true },
  'Pre-Sales Engineer': { isco: '33', isTech: true },
  'Solutions Consultant': { isco: '33', isTech: true },
  'Technical Account Manager': { isco: '33', isTech: true },
  'Customer Engineer': { isco: '33', isTech: true },
  'Partner Manager': { isco: '33', isTech: false },
  'Channel Manager': { isco: '33', isTech: false },

  // ISCO 34 — Legal, Social & Cultural Associate Professionals
  'Social Media Manager': { isco: '34', isTech: false },
  'Content Strategist': { isco: '34', isTech: false },
  'Content Marketing Manager': { isco: '34', isTech: false },
  'SEO Specialist': { isco: '34', isTech: false },
  'SEM Manager': { isco: '34', isTech: false },
  'Public Relations Manager': { isco: '34', isTech: false },
  'Event Manager': { isco: '34', isTech: false },

  // ISCO 41 — Admin support (catch-all)
  'Administrative Assistant': { isco: '41', isTech: false },
  'Executive Assistant': { isco: '41', isTech: false },

  // Independent/Special
  'Freelance Developer': { isco: '25', isTech: true },
  'Independent Consultant': { isco: '24', isTech: false },
  'Startup Founder': { isco: '13', isTech: true },
};
